# Ansible playbook for deleting ProxyTCP
---
- hosts: proxy
  gather_facts: no
  become: yes
  vars: 
    linux_user: "ubuntu"
  tasks:

    - name: Wait for system to become reachable over ssh
      wait_for_connection:
        timeout: 120
    
    - name: Gather facts for first time
      setup:

    - name: Delete proxy directory.
      file:
        state: absent
        path: /home/{{ linux_user }}/proxytcp/